
<?php $this->inlineScript()->appendFile($this->basePath() . '/assets/mot-attendance/js/sample.js'); 
$this->headLink()->prependStylesheet($this->basePath() . '/assets/datatables/media/css/jquery.dataTables_themeroller.css')
            ->prependStylesheet($this->basePath() . '/assets/datatables/extras/TableTools/media/css/TableTools.css')
            ->prependStylesheet($this->basePath() . '/assets/datatables/media/css/jquery.dataTables.min.css')
            ->prependStylesheet($this->basePath() . '/assets/jquery-ui/themes/humanity/theme.css')
            ->prependStylesheet($this->basePath() . '/assets/jquery-ui/themes/humanity/jquery-ui.min.css');
    
    
    $this->inlineScript()
            ->prependFile($this->basePath('assets/mot-attendance/js/datatable.js'))
            ->prependFile($this->basePath('assets/datatables/extras/TableTools/media/js/TableTools.js'))
            ->prependFile($this->basePath('assets/datatables/extras/TableTools/media/js/ZeroClipboard.js'))
            ->prependFile($this->basePath('assets/datatables/media/js/jquery.dataTables.min.js'))
            ->prependFile($this->basePath('assets/jquery-ui/jquery-ui.min.js'));
    
    $this->inlineScript()->captureStart();
    echo '
        $(function() {
            $( "#accordion" ).accordion();
        }); 
        ';
    $this->inlineScript()->captureEnd();
?>
<div class="pageheader">
     <div class="media">
         <div class="pageicon pull-left">
             <i class="fa fa-calendar"></i>
         </div>
         <div class="media-body" style="padding-left: 5px">
             <ul class="breadcrumb">
                 <li>
                     <a href="<?php echo $this->url('mot');?>"><i class="glyphicon glyphicon-home"></i></a>
                 </li>
                 <li><a href="#">Attendance</a></li>
                 <li>Summary Report</li>
             </ul>
             <h4>Attendance Summary Report</h4>
         </div>
     </div>
</div>
<div class="contentpanel">
    <div class="row">
        <div class="row">
            <div class="col-lg-6 col-md-6">
                <select>
                    <?php echo $employee;?>
                </select>
                <input type="date">&nbsp;&nbsp;<i class="fa fa-calendar fa-2x"></i>
                <input type="date">&nbsp;&nbsp;<i class="fa fa-calendar fa-2x"></i>
                &nbsp;&nbsp;<button class="btn btn-default">View</button>
            </div>
            <div class="col-lg-6 col-md-6"></div>
        </div>
        <br>
        <div class="row">
            <div class="col-lg-6 col-md-6">
              
                <div style="background-color:#D8D8D8" align="center">
                    <br>
                    <p align="right"><strong>Date: </strong><?php echo date("m/d/Y");?>&nbsp;&nbsp;</p>
                    <strong>Summary Report</strong>
                    
                    <?php
                    echo "<p><strong>From </strong>{$details['from']}&nbsp;&nbsp;&nbsp;&nbsp;<strong>To </strong>{$details['to']}</p>
                        <p>
                            <strong>NAME: </strong>{$details['name']}&nbsp;&nbsp;&nbsp;&nbsp;<strong>EMP ID: </strong>{$details['emp_id']} 
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <strong>DEPT: </strong>{$details['dept']}&nbsp;&nbsp;&nbsp;&nbsp;<strong>POSITION: </strong>{$details['position']}
                        </p>";
                    ?>
                    <br>
                </div>  
                 <?php foreach ($this->result AS $data) {
                echo "<div> {$this->DataTables($data['name'], $data['header'], $data['data'])} </div>";
            } ?>
              
            </div>
            <div class="col-lg-6 col-md-6">
                 <div class="col-md-1"></div>    
            <div class="col-md-10 table-responsive">
            <h2 align="left">Attendance Dispute Requests</h2>
            <table class="table ">
              <tr>
                <th>Employee</th>
                <th>Dispute Date</th>
                <th>Date Created</th>		
                <th>Dept.</th>
                <th>Branch</th>
                <th>Log Type</th>
               <th>Action</th>
               </tr>
              <tr>
                <td>Maria Aguanta</td>  
                <td>10/14/2014</td>
                <td>10/15/2014</td>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    <a  data-toggle="modal" href="#dispute">
                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true">&nbsp;&nbsp;&nbsp;</span>
                    </a>

                </td>
              </tr>
            </table>
        </div>
        <div class="col-md-1"></div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6 col-md-6"></div>
            <div class="col-lg-6 col-md-6">
                <div class="col-md-1"></div>    
            <div class="col-md-10 table-responsive">
            <h2 align="left">Dispute Request Completed</h2>
            <table class="table">
              <tr>
                <th>Employee</th>
                <th>Dispute Date</th>
                <th>Date Created</th>		
                <th>Branch</th>
                <th>Status</th>
                <th>By</th>
                <th>Comment</th>
              </tr>
              <tr>
                <td>Pedro Batonghinog</td>  
                <td>10/14/2014</td>
                <td>10/15/2014</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
            </table>
        </div>
        <div class="col-md-1"></div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="dispute" tabindex="-1" data-backdrop="static" data-keyboard="false" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel" align="left">Attendance Dispute Request Form</h4>
      </div>
      <div class="modal-body">
          <div class="row">
              <div class="col-md-1 col-lg-1"></div>
              <div class="col-lg-10 col-md-10">
              <p><strong>Reason:</strong> Computer malfunctioned</p>
              <p><strong>Effect:</strong> Change time in from 9:15AM to 9:00AM</p>
              </div>
              <div class="col-md-1 col-lg-1"></div>
          </div>    
          <div class="row"> 
              <div class="col-md-1"></div>
              <div class="col-md-10" align="center">
                    <textarea rows="5" placeholder="Your comment here..."></textarea>                    
              </div>
              <div class="col-md-1"></div>
          </div>
      </div>    
      <div class="modal-footer">
        <button type="button" class="btn btn-default">Deny</button>
        <button type="button" class="btn btn-primary">Approve</button>
      </div>
    </div>
  </div>
</div>
