<!-- 
/**
* The MIT License
*
* Copyright (c) 2012-2014, contributors of Mega Mitch Credit, Inc. software project.
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE.
*/
-->

<?php $this->inlineScript()->appendFile($this->basePath() . '/assets/mot-attendance/js/sample.js'); ?>
<div class="row">    
   
    <div class="row">
         <div class="col-md-1"></div>    
        <div class="col-md-10">
        <h2 align="left">Attendance Dispute Requests</h2>
        <table class="table table-responsive"style="width: 100%">
          <tr>
            <th>Employee</th>
            <th>Dispute Date</th>
            <th>Date Created</th>		
            <th>Dept</th>
            <th>Branch</th>
            <th>Log Type</th>
            <th>Reason</th>
            <th>Effect</th>
            <th>Action</th>
           </tr>
          <tr>
            <td>Maria Aguanta</td>  
            <td>10/14/2014</td>
            <td>10/15/2014</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <a  data-toggle="modal" href="#dispute">
                    <span class="glyphicon glyphicon-ok" aria-hidden="true">&nbsp;&nbsp;&nbsp;</span>
                </a>
                <a  data-toggle="modal" href="#dispute">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                </a>
                    
            </td>
          </tr>
        </table>
    </div>
    <div class="col-md-1"></div>
    </div>
    
    <div class="row">
         <div class="col-md-1"></div>    
        <div class="col-md-10">
        <h2 align="left">Dispute Request Completed</h2>
        <table class="table table-responsive" style="width: 100%">
          <tr>
            <th>Employee</th>
            <th>Dispute Date</th>
            <th>Date Created</th>		
            <th>Branch</th>
            <th>Status</th>
            <th>By</th>
            <th>Comment</th>
          </tr>
          <tr>
            <td>Pedro Batonghinog</td>  
            <td>10/14/2014</td>
            <td>10/15/2014</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        </table>
    </div>
    <div class="col-md-1"></div>
    </div>
   
    
</div>

<!-- Modal -->
<div class="modal fade" id="dispute" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel" align="left">Attendance Dispute Request Form</h4>
      </div>
      <div class="modal-body">
       
          <div class="row"> 
              <div class="col-md-1"></div>
              <div class="col-md-10" align="center">
                  
                    <p>You <strong>approved/denied</strong> the dispute request of Maria Agwanta.</p>
                    <textarea rows="5" placeholder="Your comment here..."></textarea>
                                      
              </div>
              <div class="col-md-1"></div>
          </div>
      </div>    
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </div>
</div>
