<div class="row">
   
    <div class=" col-lg-12 col-md-12 col-xs-12 table-responsive">
        <table class="table table-bordered table-striped">
            <tr>
                <th colspan="2" align="center">Destination</th>
                <th rowspan="2" align="center">Purpose</th>
                <th colspan="2" align="center">Expenses</th>
                <th rowspan="2" align="center">Date</th>
                <th rowspan="2" align="center">Time</th>
            </tr>
            
            <tr>
                <td>From</td>
                <td>To</td>
                <td>Description</td>
                <td>Amount</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </table>
        
        <div align="right">
            <button class="btn btn-default" type="button">Submit</button>
            <button class="btn btn-default" type="button">
                <i class="fa fa-plus-circle"></i>
            </button>
        </div> 
    </div>
</div>
