
<?php $this->inlineScript()->appendFile($this->basePath() . '/assets/mot-attendance/js/sample.js'); ?>
<div class="pageheader">
     <div class="media">
         <div class="pageicon pull-left">
             <i class="fa fa-calendar"></i>
         </div>
         <div class="media-body" style="padding-left: 5px">
             <ul class="breadcrumb">
                 <li>
                     <a href="<?php echo $this->url('mot');?>"><i class="glyphicon glyphicon-home"></i></a>
                 </li>
                 <li><a href="#">Attendance</a></li>
                 <li>Attendance Record</li>
             </ul>
             <h4>OB Status Monitoring</h4>
         </div>
     </div>
</div>
<div class="contentpanel">

    <div class="row">
        <div class="col-md-1"></div>    
        <div class="col-md-10">
            <h2 align="left">Attendance</h2>
            <table class="table table-bordered table-striped">
              <tr>
                <th>Work Date</th>
                <th>Day</th>		
                <th>Type</th>
                <th>In</th>
                <th>Out</th>		
                <th>Remarks</th>
                <th class="col-lg-1 col-md-1">Action</th>
              </tr>
              <?php var_dump($recordSet); ?>
            </table>
        </div>
        <div class="col-md-1"></div>
    </div>
   
</div>
