<!-- 
/**
* The MIT License
*
* Copyright (c) 2012-2014, contributors of Mega Mitch Credit, Inc. software project.
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE.
*/
-->

<?php $this->inlineScript()->appendFile($this->basePath() . '/assets/mot-attendance/js/sample.js'); ?>
<div class="row">
    <div class="col-md-1"></div>    
    <div class="col-md-10">
        <h2 align="left">Attendance</h2>
        <table class="table table-striped">
          <tr>
            <th>Work Date</th>
            <th>Day</th>		
            <th>Type</th>
            <th>In</th>
            <th>Out</th>		
            <th>Comment</th>
            <th>Action</th>
          </tr>
          <tr>
            <td>10/14/2014</td>
            <td>Tue</td>		
            <td>Logged</td>
            <td>08:38</td>		
            <td>12:38</td>
            <td></td>
            <td><button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#dispute">
                Dispute
              </button>
            </td>
          </tr>
        </table>
    </div>
    <div class="col-md-1"></div>
</div>


<!-- Modal -->
<div class="modal fade" id="dispute" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel" align="left">Attendance Dispute Request Form</h4>
      </div>
      <div class="modal-body">
       
          <div class="row"> 
              <div class="col-md-1"></div>
              <div class="col-md-10">
                  
                    <p><strong>Name:</strong> Maria Agwanta</p>

                    <div class="row">
                        <div class="col-md-6">
                        <p><strong>Dispute Date:</strong>10/14/2014<p>
                        </div>
                        <div class="col-md-6" align="right">
                        <p><strong>Date Created:</strong>10/15/2014</p>
                        </div>         
                    </div>
                  
                    <div class="row">
                    <div class="col-md-6">
                        <strong>Dispute reason/cause</strong>
                    </div>
                    <div class="col-md-6">
                        <strong>Dispute outcome/effect</strong>
                    </div>
                    </div>
                    
                    <div class="row" align="center">
                    <div class="col-md-6">
                        <textarea rows="4"></textarea>
                    </div>
                    <div class="col-md-6" align="right">
                        <textarea rows="4"></textarea><br>
                    </div>
                    </div>
                    
              </div>
              <div class="col-md-1"></div>
          </div>
      </div>    
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </div>
</div>
