<?php $this->inlineScript()->appendFile($this->basePath() . '/assets/mot-attendance/js/sample.js'); ?>

<div class="row">
    
    <div class="col-lg-6 col-md-6 table-responsive">
        <div>
            <select>
                <option>Option1</option>
                <option>Option2</option>
                <option>Option3</option>
            </select>
            <input type="date">&nbsp;&nbsp;<i class="fa fa-calendar fa-2x"></i>
            <input type="date">&nbsp;&nbsp;<i class="fa fa-calendar fa-2x"></i>
        </div>
        <br>
        <table class="table">
            <div style="background-color:#D8D8D8" align="center">
                <br>
                <p align="right"><strong>Date: </strong>10/25/2014&nbsp;&nbsp;</p>
                <strong>Summary Report</strong>
                <p><strong>From</strong> 10/14/2014&nbsp;&nbsp;&nbsp;&nbsp;<strong>To</strong>10/26/2014</p>
                <p>
                    <strong>NAME: </strong>Maria Aguanta&nbsp;&nbsp;&nbsp;&nbsp;<strong>EMP ID: </strong>01-0018 
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <strong>DEPT:</strong>Sales&nbsp;&nbsp;&nbsp;&nbsp;<strong>POSITION:</strong> Credit Officer
                </p>
                <br>
            </div>  
            
            <tr bgcolor="#F0F0F0 ">
                <th>Work Date</th> 
                <th>Day</th>
                <th>Type</th>
                <th colspan="2">Actual Time</th>
                <th>Late In</th>
                <th>Early Out</th>
                <th>Brk Total</th>
                <th>Remarks</th>
            </tr>
            <tr>
                <td>10/14/2014</td>
                <td>Tue</td>
                <td>Logged</td>
                <td>8:47</td>
                <td>18:10</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>10/15/2014</td>
                <td>Wed</td>
                <td>Logged</td>
                <td>9:04</td>
                <td>11:57</td>
                <td>4</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr bgcolor="red">
                <td><font color="white">10/16/2014</font></td>
                <td><font color="white">Thu</font></td>
                <td><font color="white">-</font></td>
                <td><font color="white">-</font></td>
                <td><font color="white">-</font></td>
                <td><font color="white">-</font></td>
                <td><font color="white">-</font></td>
                <td><font color="white">-</font></td>
                <td><font color="white">Holiday</font></td>
            </tr>
        </table>
        <div id="attendance-raw-data">
            <h3>Attendance Raw Data</h3>
            <table class="table">
                <tr>
                    <th>Work Date</th> 
                    <th>Day</th>
                    <th>Type</th>
                    <th colspan="2">Actual Time</th>
                    <th>Edit Data</th>
                    <th>Comment</th>
                </tr>
                <tr>
                    <td>10/14/2014</td> 
                    <td>Tue</td>
                    <td>Logged</td>
                    <td>8:38</td>
                    <td></td>
                    <td><a data-toggle="modal" href="#edit"><span class="glyphicon glyphicon-edit"></span></a></td>
                    <td></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-lg-6 col-md-6">
        <div class="row">    
   
    <div class="row">
         <div class="col-md-1"></div>    
        <div class="col-md-10 table-responsive">
        <h2 align="left">Attendance Dispute Requests</h2>
        <table class="table ">
          <tr>
            <th>Employee</th>
            <th>Dispute Date</th>
            <th>Date Created</th>		
            <th>Dept.</th>
            <th>Branch</th>
            <th>Log Type</th>
            <th>Reason</th>
            <th>Effect</th>
            <th>Action</th>
           </tr>
          <tr>
            <td>Maria Aguanta</td>  
            <td>10/14/2014</td>
            <td>10/15/2014</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <a  data-toggle="modal" href="#dispute">
                    <span class="glyphicon glyphicon-ok" aria-hidden="true">&nbsp;&nbsp;&nbsp;</span>
                </a>
                <a  data-toggle="modal" href="#dispute">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                </a>
                    
            </td>
          </tr>
        </table>
    </div>
    <div class="col-md-1"></div>
    </div>
    
    <div class="row">
         <div class="col-md-1"></div>    
        <div class="col-md-10 table-responsive">
        <h2 align="left">Dispute Request Completed</h2>
        <table class="table " >
          <tr>
            <th>Employee</th>
            <th>Dispute Date</th>
            <th>Date Created</th>		
            <th>Branch</th>
            <th>Status</th>
            <th>By</th>
            <th>Comment</th>
          </tr>
          <tr>
            <td>Pedro Batonghinog</td>  
            <td>10/14/2014</td>
            <td>10/15/2014</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        </table>
    </div>
    <div class="col-md-1"></div>
    </div>
    
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    <button class="btn btn-primary">Complete</button>
                </div>
                <div class="col-md-1"></div>
            </div>        
   
    
</div>

<!-- Modal -->
<div class="modal fade" id="dispute" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel" align="left">Attendance Dispute Request Form</h4>
      </div>
      <div class="modal-body">
       
          <div class="row"> 
              <div class="col-md-1"></div>
              <div class="col-md-10" align="center">
                  
                    <p>You <strong>approved/denied</strong> the dispute request of Maria Agwanta.</p>
                    <textarea rows="5" placeholder="Your comment here..."></textarea>
                                      
              </div>
              <div class="col-md-1"></div>
          </div>
      </div>    
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel" align="left">Edit Data</h4>
      </div>
      <div class="modal-body">
       
          <div class="row"> 
              <div class="col-md-1"></div>
              <div class="row col-md-10" align="left">
                  <div class="col-md-3"></div>
                  <div class="col-md-6">
                    <strong>Edit</strong>  
                    <input type="text" placeholder="Input new value"><br><br>
                    <strong>Comment:</strong>
                    <textarea rows="5" placeholder="Your comment here..."></textarea>
                  </div>
                  <div class="col-md-3"></div>
              </div>
              <div class="col-md-1"></div>
          </div>
      </div>    
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </div>
</div>
    </div>
</div>