<!--/**
* The MIT License
*
* Copyright (c) 2012-2014, contributors of Mega Mitch Credit, Inc. software project.
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE.
*-->


<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <h4 align="left">Leave Application Form</h4>
        <hr>
        <p><strong>Name:</strong> Maria Agwanta</p>
        <p><strong>Date Created:</strong>10/15/2014</p>
       
        <br>    
    <div class="row">
    <div class="col-md-6">
        <strong>From</strong>
    </div>
    <div class="col-md-6">
        <strong>To</strong>
    </div>
    </div>
        
    <div class="row" align="center">
    <div class="col-md-6">
        <input type="date" placeholder="Date">
    </div>
    <div class="col-md-6">
        <input type="date" placeholder="Date"><br>
    </div>
    </div>
        <br><br>
    
    <div align="center">    
         <label class="radio-inline">
            <input type="radio" id="inlineRadio1"name="pay" value="option1"> With Pay
         </label>
         <label class="radio-inline">
         <input type="radio" id="inlineRadio2" name="pay" value="option2"> Without Pay
         </label>
    </div>    
      <br>
        <strong>Reason</strong>         
    <textarea class="form-control" rows="4"></textarea>
    <br>
    <div align="right">
        <button class="btn btn-default" type="button">Cancel</button>
	<button class="btn btn-default" type="button">Submit</button>
    </div>    
    </div>
    <div class="col-md-4"></div>
</div>
