<div class="pageheader">
     <div class="media">
         <div class="pageicon pull-left">
             <i class="fa fa-briefcase"></i>
         </div>
         <div class="media-body" style="padding-left: 5px">
             <ul class="breadcrumb">
                 <li>
                     <a href="<?php echo $this->url('mot');?>"><i class="glyphicon glyphicon-home"></i></a>
                 </li>
                 <li><a href="#">Official Business</a></li>
                 <li>Approval</li>
             </ul>
             <h4>OB Approval</h4>
         </div>
     </div>
</div>
<div class="contentpanel">
    <div>
        <table class="table table-bordered">
            <tr>
                <th rowspan="2">Name</th>
                <th rowspan="2">Branch</th>
                <th rowspan="2">Department</th>
                <th rowspan="2">Type</th>
                <th rowspan="2">Date</th>
                <th rowspan="2">Time</th>
                <th colspan="2">Destination</th>
                <th rowspan="2">Purpose</th>
                <th colspan="2">Expenses</th>
                <th rowspan="2">Action</th>
            </tr>
            <tr>
                <td>From</td>
                <td>To</td>
                <td>Description</td>
                <td>Amount</td>
            </tr>
            <?php echo $data;?>
        </table>
    </div>

    
</div>
