<div>
    <table class="table table-bordered">
        <tr>
            <th rowspan="2">Name</th>
            <th rowspan="2">Branch</th>
            <th rowspan="2">Department</th>
            <th rowspan="2">Type</th>
            <th rowspan="2">Date</th>
            <th rowspan="2">Time</th>
            <th colspan="2">Destination</th>
            <th rowspan="2">Purpose</th>
            <th colspan="2">Expenses</th>
            <th rowspan="2">Action</th>
        </tr>
        <tr>
            <td>From</td>
            <td>To</td>
            <td>Description</td>
            <td>Amount</td>
        </tr>
        <?php echo $data;?>
    </table>
</div>

