<?php // $this->inlineScript()->prependFile("http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js");
    $this->inlineScript()->prependFile($this->basePath() . '/js/addrow.js');?>


<div>
    <div class="table-responsive">
        <table class="table table-bordered">
            <tr>
                <th rowspan="2">Date</th>
                <th rowspan="2">Status</th>
                <th rowspan="2">Processed by</th>
                <th rowspan="2">Comment</th>
                <th rowspan="2">Type</th>
                <th rowspan="2">Date Requested</th>
                <th rowspan="2">Time Requeested</th>
                <th colspan="2">Destination</th>
                <th rowspan="2">Purpose</th>
                <th colspan="2">Expenses</th>
                <th colspan="2">OB Timestamp</th>
            </tr>
            <tr>
                <td>From</td>
                <td>To</td>
                <td>Description</td>
                <td>Amount</td>
                <td>OB out</td>
                <td>OB in</td>
            </tr>
            <tr>
                <?php echo $data;?>
            </tr>
        </table>
    </div>
</div>