<div class="table-responsive">
    <table class="table table-bordered">
        <tr>
            <th rowspan="2">Status</th>
            <th rowspan="2">Processed by</th>
            <th rowspan="2">Comment</th>
            <th rowspan="2">Type</th>
            <th rowspan="2">Date</th>
            <th rowspan="2">Time</th>
            <th colspan="2">Destination</th>
            <th rowspan="2">Purpose</th>
        </tr>
        <tr>
            <td>From</td>
            <td>To</td>
        </tr>
        <?php echo $data;?>
   </table>
</div>