
<?php $this->inlineScript()->prependFile($this->basePath() . '/js/addrow.js');?>

<div class="row">
    <div class="col-lg-1 col-md-1"></div>
    <div class=" col-lg-10 col-md-10 table-responsive">
        <table id="rowTable" class="table table-bordered">
            <tr>
                <th colspan="2" align="center">Destination</th>
                <th rowspan="2" align="center">Purpose</th>
                <th colspan="2" align="center">Expenses</th>
                <th rowspan="2">Action</th>
            </tr>
            
            <tr>
                <td>From</td>
                <td>To</td>
                <td>Description</td>
                <td>Amount</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td class="col-md-1">
                    <button class="btn btn-default btn-mini" id="deleteRow" value="Delete Row" type="button">
                        <i class="fa fa-minus-circle"></i>
                    </button>
                    
                </td>
            </tr>
        </table>
        
        <div align="right">
            <button class="btn btn-default" type="button">Submit</button>
            <button class="btn btn-default" id="addRowRegular" value="Add Row" type="button">
                <i class="fa fa-plus-circle"></i>
            </button>
        </div> 
    </div>
    <div class="col-lg-1 col-md-1"></div>
</div>

