<!--/**
* The MIT License
*
* Copyright (c) 2012-2014, contributors of Mega Mitch Credit, Inc. software project.
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE.
*-->

<div class="row">
    <div class="col-lg-1 col-md-1"></div>
    <div class=" col-lg-10 col-md-10 table-responsive">
        <table class="table table-bordered table-striped">
            <tr>
                <th colspan="2" align="center">Destination</th>
                <th rowspan="2" align="center">Purpose</th>
                <th colspan="2" align="center">Expenses</th>
            </tr>
            
            <tr>
                <td>From</td>
                <td>To</td>
                <td>Description</td>
                <td>Amount</td>
            </tr>
            <tr>
                <td><input class="input-sm" type="text" padding="0" margin="0"></td>
                <td><input class="input-sm" type="text" padding="0" margin="0"></td>
                <td><input class="input-sm" type="text" padding="0" margin="0"></td>
                <td><input class="input-sm" type="text" padding="0" margin="0"></td>
                <td><input class="input-sm" type="text" padding="0" margin="0"></td>
            </tr>
        </table>
        
        <div align="right">
            <button class="btn btn-default" type="button">Submit</button>
            <button class="btn btn-default" type="button">
                <i class="fa fa-plus-circle"></i>
            </button>
        </div> 
    </div>
    <div class="col-lg-1 col-md-1"></div>
</div>

